### PR TITLE
@stefanpenner WIP on adding linkdir support

### PR DESCRIPTION
**Pull request by hjdivad**
- [x] not getting linkdir commands in merge-trees; problem could be here or in merge-trees
- [x] merge-trees needs a test for the unlinkdir case
- [x] merge-trees will need an unlinkdir impl that doesn't just throw

### CODE REVIEW

**Comment by hjdivad** [comment]
@stefanpenner ping

**Comment by hjdivad** [comment]
Optional


- [ ] skip optimisation if platform no has linking
- [ ] update fs-tree-diff-docs re: `linkDir`

**Comment by stefanpenner** [comment]
> skip optimisation if platform has no linking

Im not sure this is optional, i think non-linking platforms wont work with the optimization.

**Comment by hjdivad** [comment]
@stefanpenner it depends on what `symlinkOrCopySync(PATH_TO_DIR, PATH)` does.  If that has `cp -r` semantics then builds should produce the right output, but won't benefit from tree diffing where we try to use the optimisation but fail b/c the platform doesn't support it.

So for example if we try to link directory `foo`, then modify something in `foo`, a rebuild will `rm -rf ./output/foo && cp -r ./input/foo ./output` instead of properly diffing `foo`.

That said, adding support for skipping the optimisation on windows should be pretty easy since it mostly amounts to tweaking the conditionals at the end of `_mergeRelativePath`

**Comment by stefanpenner** [comment]
@hjdivad ah ok, yes if we rm -rf + recopy on those platforms it will work as expected. We can do some perf analysis later and see if we should bring the optimization via diffing + patching back or not. (my guess is it will be a win)

**Comment by hjdivad** [comment]
@stefanpenner okay i think this is ready to merge

**Comment by hjdivad** [comment]
@stefanpenner one minor thing: we didn't *really* need new commands, as you could infer what to do from `mkdir, linkDir` and `rmdir, linkDir` although `linkdir` and `unlinkdir` do seem way more clear.

**Pull request merged**
